### ISSUE TITLE
Github issues resource exceeds API rate limits and makes pipelines fail. 

### ISSUE THREAD

**Issue by feoh** [mitodl/ol-concourse-github-issues#71]
Currently, several pipelines are failing intermittently depending on whether or
not we've exceeded our hourly Github API rate limit. This is unacceptable in the
extreme.

[Example](https://cicd.odl.mit.edu/teams/infrastructure/pipelines/docker-packer-pulumi-dagster/jobs/deploy-ol-infrastructure-dagster-server-applications.dagster.qa/builds/295).

### Expected Behavior
the github-issues-resource should never fail the pipeline under normal conditions. It should act as a gate for any given stage.

### Current Behavior

[Example](https://cicd.odl.mit.edu/teams/infrastructure/pipelines/docker-packer-pulumi-dagster/jobs/deploy-ol-infrastructure-dagster-server-applications.dagster.qa/builds/295).
### Possible Solution

I honestly do not see a solution with the current design we have, and trying to visualize new designs has been problematic since the source of truth for this sytem is the Github API. We could run some kind of intermiediate cache but then there are freshness issues.

**Comment by pdpinch** [comment]
Which API is failing?

I looked at the linked examples, but it wasn't clear to me.

**Comment by feoh** [comment]
@Ardiea reported that the Github API was hitting rate limits causing the concourse-github-issues Concourse custom resource to fail.

**Comment by feoh** [comment]
I am out of ideas on this issue.

All attempts to switch the resouce to use MIT's github Enterprise Github instance have failed due to errors around Bad Credentials [example](https://cicd.odl.mit.edu/teams/infrastructure/pipelines/packer-pulumi-tika/jobs/deploy-ol-infrastructure-tika-server-applications.tika.ci/builds/1072).

Despite setting base_url to a number of different values I couldn't get the API to not go to the main Github site.

I saved my work in [this branch](https://github.com/mitodl/ol-concourse-github-issues/tree/cpatti_mit_github) in case others have ideas that would help get us closer to a solution.

**Comment by feoh** [comment]
I created [this branch](https://github.com/mitodl/ol-infrastructure/tree/cpatti_gh_issues_use_mit) on ol-infrastructure with the changes I made there as well.

@Ardiea is going to take a look at this next week and see if he has any ideas as to where we can optimize.

**Comment by feoh** [comment]
Long since resolved by moving to MIT github.
